apalis-imx8: fix addresses to align with MEK platform
This fixes distroboot script invocation and finally gets Linux
kernel booting:

ERROR: Did not find a cmdline Flattened Device Tree
FDT and ATAGS support not compiled in - hanging
ERROR ### Please RESET the board

With this fix kernel boots:
=> boot
MMC: no card present
MMC: no card present
switch to partitions #0, OK
mmc0(part 0) is current device
Scanning mmc 0:1...
Found U-Boot script /boot.scr
1243 bytes read in 14 ms (85.9 KiB/s)
106496 bytes read in 13 ms (7.8 MiB/s)
Loading hdp firmware from 0x000000009c000000 offset 0x0000000000002000
Loading hdp firmware Complete
105758 bytes read in 15 ms (6.7 MiB/s)
21563904 bytes read in 650 ms (31.6 MiB/s)
   Booting using the fdt blob at 0x83800000
   Loading Device Tree to 00000000fd634000, end 00000000fd650d1d ... OK
Starting kernel ...
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.14.170-3.0.4+gbaa6c24240a4 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP PREEMPT Tue Apr 21 04:11:13 UTC 2020
[    0.000000] Boot CPU: AArch64 Processor [410fd034]
[    0.000000] Machine model: Toradex Apalis iMX8QM/QP on Apalis Evaluation Board
[    0.000000] efi: Getting EFI parameters from FDT:
[    0.000000] efi: UEFI not found.
[    0.000000] Reserved memory: created CMA memory pool at 0x0000000096000000, size 960 MiB
[    0.000000] OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
[    0.000000] Reserved memory: created DMA memory pool at 0x0000000090400000, size 28 MiB
[    0.000000] OF: reserved mem: initialized node rpmsg_dma@0x90400000, compatible id shared-dma-pool
[    0.000000] NUMA: No NUMA configuration found
[    0.000000] NUMA: Faking a node at [mem 0x0000000080200000-0x00000008ffffffff]
[    0.000000] NUMA: NODE_DATA [mem 0x8fff5a780-0x8fff5c57f]
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000080200000-0x00000000ffffffff]
[    0.000000]   Normal   [mem 0x0000000100000000-0x00000008ffffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000080200000-0x0000000083ffffff]
[    0.000000]   node   0: [mem 0x0000000086400000-0x000000008fffffff]
[    0.000000]   node   0: [mem 0x0000000094c00000-0x00000000ffffffff]
[    0.000000]   node   0: [mem 0x0000000880000000-0x00000008ffffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000080200000-0x00000008ffffffff]
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: PSCIv1.1 detected in firmware.
[    0.000000] psci: Using standard PSCI v0.2 function IDs
[    0.000000] psci: MIGRATE_INFO_TYPE not supported.
[    0.000000] psci: SMC Calling Convention v1.1
[    0.000000] percpu: Embedded 23 pages/cpu s53656 r8192 d32360 u94208

Relates-to: ELB-2927
Signed-off-by: Igor Opaniuk <igor.opaniuk@toradex.com>